"""
Email Generation Prompt — Version 1

System prompt: Static. Loaded once.
User prompt: Built dynamically per contact.
Output: EmailGenerationOutput (Pydantic model with tokens_used field).

Do NOT edit this file. Create email_generation_v2.py for changes.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from app.core.logging import get_logger

logger = get_logger(__name__)

SYSTEM_PROMPT = """You are an expert cold email writer specializing in job outreach for technical professionals.

Your emails are:
- Highly personalized to the recipient and their company
- Concise (under 200 words in the body)
- Focused on value to the recipient, not the sender's needs
- Professional but human — not corporate-speak
- Never generic or templated-sounding

You always write in first person as the job seeker.
You never use clichés like "I hope this email finds you well" or "I wanted to reach out".
"""


class EmailGenerationOutput(BaseModel):
    subject: str = Field(description="Email subject line — concise and relevant")
    body: str = Field(description="Email body — plain text, under 200 words")
    reasoning: str = Field(description="Brief explanation of personalization choices made")
    tokens_used: int = Field(default=0, description="Estimated tokens used (provider fills this)")


def build_user_prompt(
    sender_name: str,
    sender_background: str,
    contact: object,
    personalization_notes: str,
    past_performance: str,
    tone: str,
    job_title: str | None,
) -> str:
    """Build the user-facing prompt with all dynamic context injected."""

    # Access contact and company attributes (Contact ORM model)
    contact_name = getattr(contact, "full_name", "")
    contact_title = getattr(contact, "title", "") or ""
    company = getattr(contact, "company", None)
    company_name = getattr(company, "name", "") if company else ""
    company_description = getattr(company, "description", "") or ""
    company_industry = getattr(company, "industry", "") or ""

    job_section = f"\nTarget job title: {job_title}" if job_title else ""

    perf_section = (
        f"\nPast email performance context:\n{past_performance}"
        if past_performance
        else ""
    )

    return f"""Write a cold outreach email with the following context:

SENDER:
- Name: {sender_name}
- Background: {sender_background}

RECIPIENT:
- Name: {contact_name}
- Title: {contact_title}
- Company: {company_name}
- Industry: {company_industry}
- Company description: {company_description}{job_section}

PERSONALIZATION NOTES:
{personalization_notes or "None available — use company/role context only."}
{perf_section}

TONE: {tone}

Generate a subject line and email body. Be specific, avoid generic phrases."""
