"""
Follow-Up Email Prompt — Version 1

System prompt: Static.
User prompt: Built with thread context and follow-up number.
Output: FollowUpOutput (Pydantic model).

Do NOT edit this file. Create follow_up_v2.py for changes.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

SYSTEM_PROMPT = """You are an expert at writing follow-up emails for cold job outreach.

Follow-up rules:
- Be brief (under 100 words in the body)
- Reference the original email naturally — don't just say "following up on my previous email"
- Add a small new element of value or insight if possible
- Never sound desperate or pushy
- Use a different angle than the original email if this is follow-up #2
- Always include a clear but low-pressure call to action
"""


class FollowUpOutput(BaseModel):
    subject: str = Field(description="Follow-up email subject — usually 'Re: {original_subject}'")
    body: str = Field(description="Follow-up email body — plain text, under 100 words")
    tokens_used: int = Field(default=0)


def build_user_prompt(
    sender_name: str,
    contact_name: str,
    company_name: str,
    original_subject: str,
    original_body: str,
    follow_up_number: int,
    days_since_last_email: int,
) -> str:
    return f"""Write follow-up #{follow_up_number} for this outreach:

SENDER: {sender_name}
RECIPIENT: {contact_name} at {company_name}
DAYS SINCE LAST EMAIL: {days_since_last_email}

ORIGINAL EMAIL SUBJECT: {original_subject}
ORIGINAL EMAIL BODY:
\"\"\"
{original_body}
\"\"\"

Generate a concise, non-pushy follow-up email."""
