"""
Reply Classification Prompt — Version 1

System prompt: Static.
User prompt: Built with reply body + original subject for context.
Output: ReplyClassificationOutput (Pydantic model).

Do NOT edit this file. Create reply_classification_v2.py for changes.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

SYSTEM_PROMPT = """You are an expert at classifying intent in email replies to cold job outreach emails.

Classify the reply into exactly one of these categories:
- interested: Positive signal, wants to continue the conversation
- not_interested: Explicit or clear rejection
- auto_reply: Out-of-office or automated message, not a human response
- bounced: Email delivery failure notification
- question: Human reply asking for more information before committing
- needs_review: Ambiguous — does not clearly fit any category above

Rules:
- Be precise. If unsure between two categories, choose needs_review.
- Return confidence as a float between 0.0 and 1.0.
- The reasoning field should explain the key signals that led to your classification.
"""


class ReplyClassificationOutput(BaseModel):
    classification: str = Field(
        description="One of: interested, not_interested, auto_reply, bounced, question, needs_review"
    )
    confidence: float = Field(description="Confidence score between 0.0 and 1.0", ge=0.0, le=1.0)
    reasoning: str = Field(description="Explanation of the key signals that determined this classification")
    tokens_used: int = Field(default=0)


def build_user_prompt(reply_body: str, original_subject: str) -> str:
    return f"""Original email subject: {original_subject}

Reply received:
\"\"\"
{reply_body}
\"\"\"

Classify the intent of this reply."""
